### ISSUE TITLE
組織機能の実装

### ISSUE THREAD

**Issue by yoshichiba** [hiroaki514/contents_management_app#148]
・1組織に対して複数人のユーザーが所属する
・その中には管理者と一般ユーザーがいる
・マスター権限の人はどの組織も操作できる

例：組織Aに管理者aと一般b、一般cが所属する
　　組織Bに管理者bと一般d、一般eが所属する

・.組織テーブル: organizations
　　組織名(カラム): name
　　外部キー: user_id

・アソシエーション
　　組織とユーザーは1対多

・組織毎にグループ化されて表示される

**Comment by hiroaki514** [comment]
1. テーブル作成（カラム追加）
2. モデル作成
3. モデルにアソシエーション定義
4. ロジックの実装
5. ビュー実装
6. テストの実装

**Comment by mpg-yoshiharu-chiba** [comment]
・ユーザー登録時に組織を登録できる
・組織登録画面の作成
・ユーザー編集ページで組織を変更できる

**Comment by mpg-yoshiharu-chiba** [comment]
`f.select`について調べて書いてみる。

**Comment by yoshichiba** [comment]
（次回）
・ユーザー表示
・組織登録フォームの実装

**Comment by yoshichiba** [comment]
（残タスク）
・組織一覧ページの作成
・組織の編集機能
・ユーザーの編集機能
・RSpec（テストコード）

**Comment by yoshichiba** [comment]
組織詳細の実装

**Comment by hiroaki514** [comment]
完了
