### ISSUE TITLE
論理削除の実装

### ISSUE THREAD

**Issue by yoshichiba** [hiroaki514/contents_management_app#199]

**Comment by mpg-yoshiharu-chiba** [comment]
論理削除Gem
https://techtechmedia.com/logiacal-deletion-discard/

**Comment by mpg-yoshiharu-chiba** [comment]
テスト内容

`organizations_spec`
・論理削除がされること
・論理削除された組織は一覧に表示されないこと

`lgs_spec.rb`
・ログが表示されること

**Comment by hiroaki514** [comment]
完了しました！
