### ISSUE TITLE
ログの追加

### ISSUE THREAD

**Issue by mpg-yoshiharu-chiba** [hiroaki514/contents_management_app#204]
- 誰が作成したか
  - ユーザー
  - 組織
- 誰が削除したか
  - ユーザー
  - 組織

**Comment by yoshichiba** [comment]
1. カラム追加
誰が作成したかを保存するカラムをusersテーブルに追加する。
例), created_user_id → integer型

2. created_user_idに作成者のidを保存する処理を追加

```
@user.update(created_user_id: current_user.id)
```

3. ユーザーを表示する

created_user_idがnilではないものを取得して表示する
