### ISSUE TITLE
マスター権限のみ閲覧できるページに新規ユーザー追加画面を作成する

### ISSUE THREAD

**Issue by yoshichiba** [hiroaki514/contents_management_app#62]
1. generalのindex.html.erbにマスターページへ飛ぶリンクを作成
2. masterのindex.htmlに遷移する
3. masterのindex.html.erbの中に新規ユーザー作成ページへ飛ぶリンクを作成。
4. master配下にnew.html.erbを作成。ここが登録フォームのページ。
5. new.html.erbに新規ユーザー作成画面を作成

```
master
  - index.html.erb
  - new.html.erb（新規ユーザー作成画面）
```

**Comment by hiroaki514** [comment]
完了しました
