### ISSUE TITLE
slack-ruby-clientを用いてSlack通知を実装してみる

### ISSUE THREAD

**Issue by yoshichiba** [hiroaki514/contents_management_app#97]
## 仕様
新規ユーザーが登録された際、Slackの「# new_userチャンネル」に通知が行われる。
（「# new_userチャンネル」は新規チャンネル作成してください。）

## 参考記事

- https://qiita.com/murakami-mm/items/c34af59fdff198161967
- https://github.com/slack-ruby/slack-ruby-client

**Comment by hiroaki514** [comment]
通知のテスト完了
